defaultSemverRangePrefix: ""

nodeLinker: node-modules

enableColors: true
enableImmutableInstalls: true
preferInteractive: true

npmScopes:
  hg:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/27373916/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/27373916/packages/npm/"
  hg-config:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/27373916/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/27373916/packages/npm/"
  hg-nest:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/27373916/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/27373916/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
